### ISSUE TITLE
Class Df\StripeClone\Webhook\NotImplemented contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Df\StripeClone\Webhook::roPrefix)

### ISSUE THREAD

**Issue by radoxtech** [mage2pro/facebook-login#1]
Hi.

I was installed this by instruction, on fresh installation of Magento CE, after the last command I saw this:

`radek@mail:~/www$ rm -rf var/di var/generation && php bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 76.2 MiB
PHP Fatal error:  Class Df\StripeClone\Webhook\NotImplemented contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Df\StripeClone\Webhook::roPrefix) in /home/radek/www/vendor/mage2pro/core/StripeClone/Webhook/NotImplemented.php on line 23
radek@mail:~/www$ `

I hope you can help me.
Regards
Radek

**Comment by dmitrii-fediuk** [comment]
Fixed in the latest version.
